const checklistPorTipo = {
  "Passeio": [
    "Pneus (pressão, desgaste, trincas)",
    "Rodas (porcas, trincas)",
    "Freios (pastilhas, disco, pedal)",
    "Nível de óleo do motor",
    "Nível do fluido de freio",
    "Nível de arrefecimento",
    "Direção (folga, ruídos)",
    "Iluminação externa (faróis, lanternas, ré, freio)",
    "Iluminação interna",
    "Limpadores e lavador",
    "Cinto de segurança",
    "Painel de instrumentos",
    "Extintor (validade)",
    "Triângulo, estepe, chave de roda, macaco",
    "Vazamentos visíveis",
    "Buzina"
  ],

  "Utilitário": [
    "Pneus (pressão, desgaste, trincas)",
    "Rodas (porcas, trincas)",
    "Freios (pastilhas, disco, pedal)",
    "Nível de óleo do motor",
    "Nível do fluido de freio",
    "Nível de arrefecimento",
    "Direção (folga, ruídos)",
    "Iluminação externa (faróis, lanternas, ré, freio)",
    "Iluminação interna",
    "Limpadores e lavador",
    "Cinto de segurança",
    "Painel de instrumentos",
    "Extintor (validade)",
    "Triângulo, estepe, chave de roda, macaco",
    "Vazamentos visíveis",
    "Buzina",
    "Compartimento de carga (limpeza e fixação)",
    "Amarração de carga (fitas/catracas)",
    "Travas das portas traseiras"
  ],

  "Van de Passageiros": [
    "Sistema de ar/ventilação",
    "Assentos e cintos de todos os passageiros",
    "Travamento das portas",
    "Abertura de emergência",
    "Iluminação interna/sinalização de saída",
    "Condições da carroceria e vedação",
    "Pneus (pressão, desgaste, trincas)",
    "Rodas (porcas, trincas)",
    "Freios (pastilhas, disco, pedal)",
    "Nível de óleo do motor",
    "Nível do fluido de freio",
    "Nível de arrefecimento",
    "Direção (folga, ruídos)",
    "Iluminação externa (faróis, lanternas, ré, freio)",
    "Iluminação interna",
    "Limpadores e lavador",
    "Cinto de segurança",
    "Painel de instrumentos",
    "Extintor (validade)",
    "Triângulo, estepe, chave de roda, macaco",
    "Vazamentos visíveis",
    "Buzina"
  ],

  "Van de Carga": [
    "Piso e paredes internas (rachaduras, corrosão)",
    "Presença de divisórias (se exigido)",
    "Estado do isolamento térmico (se aplicável)",
    "Pneus (pressão, desgaste, trincas)",
    "Rodas (porcas, trincas)",
    "Freios (pastilhas, disco, pedal)",
    "Nível de óleo do motor",
    "Nível do fluido de freio",
    "Nível de arrefecimento",
    "Direção (folga, ruídos)",
    "Iluminação externa (faróis, lanternas, ré, freio)",
    "Iluminação interna",
    "Limpadores e lavador",
    "Cinto de segurança",
    "Painel de instrumentos",
    "Extintor (validade)",
    "Triângulo, estepe, chave de roda, macaco",
    "Vazamentos visíveis",
    "Buzina"
  ],

  "Moto / Motocicleta": [
    "Pneus (pressão e desgaste)",
    "Corrente, coroa e pinhão (tensão/lubrificação)",
    "Freios (dianteiro/traseiro)",
    "Iluminação (farol, pisca, lanterna)",
    "Painel (luzes/alertas)",
    "Espelhos retrovisores",
    "Manetes (embreagem e freio)",
    "Vazamentos",
    "Estado geral do capacete (selo INMETRO)",
    "EPIs obrigatórios"
  ],

  "VUC – Veículo Urbano de Carga": [
    "Altura e largura compatíveis com limites urbanos",
    "Estado da carroceria/baú",
    "Sistema de freio (hidráulico ou pneumático)",
    "Itens específicos do tipo de baú, se aplicável",
    "Pneus (pressão, desgaste, trincas)",
    "Rodas (porcas, trincas)",
    "Freios (pastilhas, disco, pedal)",
    "Nível de óleo do motor",
    "Nível do fluido de freio",
    "Nível de arrefecimento",
    "Direção (folga, ruídos)",
    "Iluminação externa (faróis, lanternas, ré, freio)",
    "Iluminação interna",
    "Limpadores e lavador",
    "Cinto de segurança",
    "Painel de instrumentos",
    "Extintor (validade)",
    "Triângulo, estepe, chave de roda, macaco",
    "Vazamentos visíveis",
    "Buzina"
  ],

  "Caminhão 3/4": [
    "Pneus (calibragem, par duplo)",
    "Suspensão (molas, batentes)",
    "Sistema de freio (pedal, lonas, vazamento ar)",
    "Iluminação traseira lateral",
    "Baú (fixação, portas, vedação)",
    "Espelhos extras (convexos)",
    "Amarração de carga",
    "Disco do tacógrafo (se obrigatório)",
    "Pneus (pressão, desgaste, trincas)",
    "Rodas (porcas, trincas)",
    "Freios (pastilhas, disco, pedal)",
    "Nível de óleo do motor",
    "Nível do fluido de freio",
    "Nível de arrefecimento",
    "Direção (folga, ruídos)",
    "Iluminação externa (faróis, lanternas, ré, freio)",
    "Iluminação interna",
    "Limpadores e lavador",
    "Cinto de segurança",
    "Painel de instrumentos",
    "Extintor (validade)",
    "Triângulo, estepe, chave de roda, macaco",
    "Vazamentos visíveis",
    "Buzina"
  ],

  "Caminhão Toco": [
    "Nível do fluido de ar (manômetro)",
    "Fixação de para-lamas",
    "Estado das lonas/discos de freio",
    "Estrutura do baú/carroceria (parafusos, soldas)",
    "Sistema de exaustão (vazamento e ruído)",
    "Pneus (pressão, desgaste, trincas)",
    "Rodas (porcas, trincas)",
    "Freios (pastilhas, disco, pedal)",
    "Nível de óleo do motor",
    "Nível do fluido de freio",
    "Nível de arrefecimento",
    "Direção (folga, ruídos)",
    "Iluminação externa (faróis, lanternas, ré, freio)",
    "Iluminação interna",
    "Limpadores e lavador",
    "Cinto de segurança",
    "Painel de instrumentos",
    "Extintor (validade)",
    "Triângulo, estepe, chave de roda, macaco",
    "Vazamentos visíveis",
    "Buzina"
  ],

  "Caminhão Truck": [
    "Nível do fluido de ar (manômetro)",
    "Fixação de para-lamas",
    "Estado das lonas/discos de freio",
    "Estrutura do baú/carroceria (parafusos, soldas)",
    "Sistema de exaustão (vazamento e ruído)",
    "Pneus (pressão, desgaste, trincas)",
    "Rodas (porcas, trincas)",
    "Freios (pastilhas, disco, pedal)",
    "Nível de óleo do motor",
    "Nível do fluido de freio",
    "Nível de arrefecimento",
    "Direção (folga, ruídos)",
    "Iluminação externa (faróis, lanternas, ré, freio)",
    "Iluminação interna",
    "Limpadores e lavador",
    "Cinto de segurança",
    "Painel de instrumentos",
    "Extintor (validade)",
    "Triângulo, estepe, chave de roda, macaco",
    "Vazamentos visíveis",
    "Buzina"
  ],

  "Cavalo Mecânico": [
    "Quinta roda (lubrificação, travamento)",
    "Pino-rei (verificação visual na carreta acoplada)",
    "Conexões elétricas e pneumáticas",
    "Freios (compressor, câmaras, válvulas)",
    "Sistema de ar (secador, reservatórios)",
    "Tacógrafo obrigatório",
    "Manômetro de pressão",
    "Embreagem e transmissão (ruído e tranco)",
    "Suspensão traseira e molas pneumáticas",
    "Pneus (pressão, desgaste, trincas)",
    "Rodas (porcas, trincas)",
    "Freios (pastilhas, disco, pedal)",
    "Nível de óleo do motor",
    "Nível do fluido de freio",
    "Nível de arrefecimento",
    "Direção (folga, ruídos)",
    "Iluminação externa (faróis, lanternas, ré, freio)",
    "Iluminação interna",
    "Limpadores e lavador",
    "Cinto de segurança",
    "Painel de instrumentos",
    "Extintor (validade)",
    "Triângulo, estepe, chave de roda, macaco",
    "Vazamentos visíveis",
    "Buzina"
  ],

  "Carreta": [
    "Pneus (estado dos pares)",
    "Freios (válvulas, câmaras, regulagem)",
    "Chicote elétrico (fixação, tomadas)",
    "Amarração e distribuição da carga",
    "Sinais reflexivos e faixas laterais",
    "Fixação das tampas/portas",
    "Tipo de baú (sider, refrigerado, etc.)",
    "Estrutura inferior (rachaduras, trincas, ferrugem)"
  ],

  "Bitrem": [
    "Pneus (estado dos pares)",
    "Freios (válvulas, câmaras, regulagem)",
    "Chicote elétrico (fixação, tomadas)",
    "Amarração e distribuição da carga",
    "Sinais reflexivos e faixas laterais",
    "Fixação das tampas/portas",
    "Tipo de baú (sider, refrigerado, etc.)",
    "Estrutura inferior (rachaduras, trincas, ferrugem)"
  ],

  "Rodotrem": [
    "Pneus (estado dos pares)",
    "Freios (válvulas, câmaras, regulagem)",
    "Chicote elétrico (fixação, tomadas)",
    "Amarração e distribuição da carga",
    "Sinais reflexivos e faixas laterais",
    "Fixação das tampas/portas",
    "Tipo de baú (sider, refrigerado, etc.)",
    "Estrutura inferior (rachaduras, trincas, ferrugem)"
  ],

  "Micro-ônibus": [
    "Sistema de portas (abertura, travamento, sensores)",
    "Ar-condicionado ou ventilação interna",
    "Assentos e cintos de todos os passageiros",
    "Tacógrafo obrigatório",
    "Sinalização interna e saídas de emergência",
    "Iluminação do salão",
    "Acesso PCD (elevador/escada)",
    "Vidros e cortinas",
    "Pneus (pressão, desgaste, trincas)",
    "Rodas (porcas, trincas)",
    "Freios (pastilhas, disco, pedal)",
    "Nível de óleo do motor",
    "Nível do fluido de freio",
    "Nível de arrefecimento",
    "Direção (folga, ruídos)",
    "Iluminação externa (faróis, lanternas, ré, freio)",
    "Iluminação interna",
    "Limpadores e lavador",
    "Cinto de segurança",
    "Painel de instrumentos",
    "Extintor (validade)",
    "Triângulo, estepe, chave de roda, macaco",
    "Vazamentos visíveis",
    "Buzina"
  ],

  "Ônibus": [
    "Sistema de portas (abertura, travamento, sensores)",
    "Ar-condicionado ou ventilação interna",
    "Assentos e cintos de todos os passageiros",
    "Tacógrafo obrigatório",
    "Sinalização interna e saídas de emergência",
    "Iluminação do salão",
    "Acesso PCD (elevador/escada)",
    "Vidros e cortinas",
    "Pneus (pressão, desgaste, trincas)",
    "Rodas (porcas, trincas)",
    "Freios (pastilhas, disco, pedal)",
    "Nível de óleo do motor",
    "Nível do fluido de freio",
    "Nível de arrefecimento",
    "Direção (folga, ruídos)",
    "Iluminação externa (faróis, lanternas, ré, freio)",
    "Iluminação interna",
    "Limpadores e lavador",
    "Cinto de segurança",
    "Painel de instrumentos",
    "Extintor (validade)",
    "Triângulo, estepe, chave de roda, macaco",
    "Vazamentos visíveis",
    "Buzina"
  ],

  "Caminhão-tanque": [
    "Vedação das tampas e bocais",
    "Aterramento (fio antiestático)",
    "Sinalização de risco (placas ADR)",
    "Equipamentos obrigatórios (calço, extintor extra, cones)",
    "Ausência de vazamento nas válvulas",
    "Fixação dos tubos e mangueiras",
    "Compartimentos internos (separação de produto)",
    "Pneus (pressão, desgaste, trincas)",
    "Rodas (porcas, trincas)",
    "Freios (pastilhas, disco, pedal)",
    "Nível de óleo do motor",
    "Nível do fluido de freio",
    "Nível de arrefecimento",
    "Direção (folga, ruídos)",
    "Iluminação externa (faróis, lanternas, ré, freio)",
    "Iluminação interna",
    "Limpadores e lavador",
    "Cinto de segurança",
    "Painel de instrumentos",
    "Extintor (validade)",
    "Triângulo, estepe, chave de roda, macaco",
    "Vazamentos visíveis",
    "Buzina"
  ]
};

export default checklistPorTipo;
